<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mdotyasin</name>
   <tag></tag>
   <elementGuidId>61b8d746-990c-4d58-b1be-13f0a1d38d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sulton Daud Ul Mukarobin'])[1]/following::td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a934fb17-5450-4718-99c6-3135b4c21203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>muhammad.yasin@oti.com</value>
      <webElementGuid>c0f22481-43e8-4c4a-a5a8-53d6eaf78ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue sidebar-mini&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body table-responsive no-padding&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[4]/td[1]</value>
      <webElementGuid>93305fc9-5962-44cf-bb51-22bc14daeac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sulton Daud Ul Mukarobin'])[1]/following::td[6]</value>
      <webElementGuid>21553966-bff1-45bc-9c7f-b04b2a9f8ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sultonmukarobin@oti.com'])[1]/following::td[7]</value>
      <webElementGuid>11260c19-7136-4aa8-b5d8-83625e8542c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muhammad Yasin'])[1]/preceding::td[1]</value>
      <webElementGuid>7cc62a46-bf91-4f4e-ad74-7d86c015e928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mugen@oti.com'])[1]/preceding::td[7]</value>
      <webElementGuid>d8cb6a18-a369-4e21-bed7-be53e231efb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='muhammad.yasin@oti.com']/parent::*</value>
      <webElementGuid>c3d0f271-f3d4-4d96-93e8-c4e458d01b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td</value>
      <webElementGuid>21d8f862-b381-4e32-be06-b0af62968eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'muhammad.yasin@oti.com' or . = 'muhammad.yasin@oti.com')]</value>
      <webElementGuid>ac1c5ef5-61e4-4ce1-bcf3-4ac207983534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
